#!/bin/sh
LIBPATH="./lib"

usage() {
	echo "Usage: minutes-m4rkdown <input>"
}

if [ $# -lt 1 ]; then
	usage
	exit 1
fi

input="$1"
render_markdown_private=1
render_markdown_public=1
render_json_private=1
render_json_public=1

# TODO: parse options

# params: <output-file> <m4-lib-file> <input-files...>
render() {
	cat "$@" | m4 -I "$LIBPATH" > "$1"
}

for format in markdown json; do
	for visibility in public nonpublic; do
		varref="render_${format}_${visibility}"
		eval "do_format=\$$varref"
		if [ -n "$do_format" ]; then
			output=$(echo $input | sed 's/^\(.*\)\.[^.]\+/\1/')

			render "${output}-${visibility}.${format}" \
				"$LIBPATH/${format}-${visibility}.m4" "$input"
		fi
	done
done
